# aarch has issues with newer GCC
c_compiler_version:             # [aarch64]
  - 11                          # [aarch64]
  - 11                          # [aarch64]
cxx_compiler_version:           # [aarch64]
  - 11                          # [aarch64]
  - 11                          # [aarch64]

github_actions_labels:          # [linux]
- cirun-openstack-cpu-2xlarge   # [linux]
microarch_level:
- 1
# hmaarrfk -- temporary, uncomment during actual build
- 3   # [linux and x86_64]
