github_actions_labels:          # [linux]
- cirun-openstack-cpu-2xlarge   # [linux]
microarch_level:
- 1
- 3   # [linux and x86_64]
- 4   # [linux and x86_64]
libabseil:
- '20240722'
libgrpc:
- '1.67'
libprotobuf:
- 5.28.3
